server:
  port: 10100
spring:
  application:
    name: API-ADMINS
  cloud:
    nacos:
      server-addr: localhost:18848
  datasource:
    url: jdbc:mysql://localhost:13306/yingxue?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 阿里Druid数据库连接池配置
    druid:
      initial-size: 5    #连接池初始化大小
      min-idle: 10       #最小空闲连接数
      max-active: 20     #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        enabled: true    #开启监控页面
        url-pattern: /druid/*
        login-username: druid
        login-password: druid
  redis:
    host: localhost
    password: 123456
    port: 16379
    timeout: 3000
logging:
  level:
    com.example.mapper: debug
token:
  expire: 1800    # 过期时间（单位：秒）
